version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    expose:
      - "8000"
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend/domain-finder-ui
    container_name: frontend
    expose:
      - "80"

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /var/www/html:/var/www/html
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 6h & wait $${!}; certbot renew; done'"
