version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    expose:
      - "8000"
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend/domain-finder-ui
    container_name: frontend
    expose:
      - "80"

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
